name: Nuget Package

on:
  push:
    branches: [ master ]
    paths:
      - 'Convo/**'
      - '.github/**'

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  CURRENT_VERSION: '0.2'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      project: Convo/Convo.csproj
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $project
    - name: Build
      run: dotnet pack $project -c Release /p:PackageVersion=${{ env.CURRENT_VERSION }}.${{ github.run_number }} /p:VersionPrefix=${{ env.CURRENT_VERSION }}.${{ github.run_number }} --no-restore --include-symbols -p:SymbolPackageFormat=snupkg --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    - name: Push generated package to Nuget registry
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}